### ISSUE TITLE
multi-cluster support when using a kubeconfig

### ISSUE THREAD

**Issue by Darwin014** [sighupio/gatekeeper-policy-manager#283] opened 2021-10-20 09:14 UTC
Hi!

Can I use aws-iam-authenticator for kubeconfig?

I installed aws-iam-authenticator in docker image and run pod but it doesn't seem to load kubeconfig.
[2021-10-20 09:08:31 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-10-20 09:08:31 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-10-20 09:08:31 +0000] [1] [INFO] Using worker: gthread
[2021-10-20 09:08:31 +0000] [7] [INFO] Booting worker with pid: 7
[2021-10-20 09:08:31 +0000] [8] [INFO] Booting worker with pid: 8
[2021-10-20 09:08:41,849] INFO: RUNNING WITH AUTHENTICATION DISABLED
[2021-10-20 09:08:41,850] INFO: Attempting init with KUBECONFIG
[2021-10-20 09:08:41,859] INFO: KUBECONFIG loading failed but KUBERNETES_SERVICE_HOST environment variable found, assuming to be running inside a Kubernetes cluster
[2021-10-20 09:08:41,859] INFO: In cluster configuration loaded successfully.
[2021-10-20 09:08:42,048] INFO: RUNNING WITH AUTHENTICATION DISABLED
[2021-10-20 09:08:42,048] INFO: Attempting init with KUBECONFIG
[2021-10-20 09:08:42,056] INFO: KUBECONFIG loading failed but KUBERNETES_SERVICE_HOST environment variable found, assuming to be running inside a Kubernetes cluster
[2021-10-20 09:08:42,056] INFO: In cluster configuration loaded successfully.
Thanks

https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html
https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html

**Comment by ralgozino** [comment] 2022-01-21 18:01
Hi @Darwin014 
We've seen some issues in AWS with v0.5.0 default memory limits that resulted in the behaviour you were seeing. Could you please try increasing them or even better switching to v0.5.1 and let us know if that works for you?

Thank you

**Comment by ralgozino** [comment] 2022-05-05 10:29
I'm almost sure this is a duplicate of #355

**Comment by ralgozino** [comment] 2022-05-12 10:33
Closing as duplicate. Please reopen the issue if it the solution for #330 doesn't apply.

**Closed by ralgozino** 2022-05-12 10:33 UTC
Labels: duplicate, question
